# Generated by Django 4.0.4 on 2024-03-31 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_paciente', '0002_alter_idoso_cidade_idoso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='foto_idoso')),
                ('idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha_paciente.idoso')),
            ],
        ),
    ]
