# Generated by Django 4.0.4 on 2024-04-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_paciente', '0003_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='idoso',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='idoso',
            name='id_idoso',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
