# Generated by Django 4.0.4 on 2024-04-07 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_paciente', '0005_rename_slug_idoso_slug_idoso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idoso',
            old_name='slug_idoso',
            new_name='slug',
        ),
    ]
