# Generated by Django 4.0.4 on 2024-03-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cargo',
            field=models.CharField(choices=[('F', 'Funcionario'), ('G', 'Gerente')], max_length=1),
        ),
    ]
